export const STATUS = {
  BAD_REQUEST: 400,
  CREATED: 201,
  INTERNAL_SERVER_ERROR: 500,
  NO_CONTENT: 204,
  NOT_FOUND: 404,
  OK: 200,
  UNAUTHORIZED: 401
};

export const STATUS_MESSAGE = {
  FAIL: "fail",
  SUCCESS: "success"
};
