export const STATUS = {
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  UNAUTHORIZED: 401
};

export const STATUS_MESSAGE = {
  SUCCESS: "success",
  FAIL: "fail"
};
