#!/bin/sh

# Get the current Git branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Forbid direct commits to master or develop
if [ "$BRANCH_NAME" = "master" ] || [ "$BRANCH_NAME" = "develop" ]; then
  echo "Commits to $BRANCH_NAME branch are forbidden."
  exit 1
fi

# Visit backend
cd ../BackEnd

# Prefer global type check, because changes to one file may cause type errors in other files
yarn type-check

# Lint the staged files
npx lint-staged

cd ../Husky
# Visit backend END

# Visit frontend
cd ../FrontEnd

# Prefer global type check, because changes to one file may cause type errors in other files
yarn type-check

# Lint the staged files
npx lint-staged

cd ../Husky
# Visit frontend END
